### ISSUE TITLE
Une remarque sur le territoire de Belfort

### ISSUE THREAD

**Issue by JiPiBi** [htonchia/covid-19-France#1]
Quand vous regardez les décès attribués au Territoire de Belfort avec les données INSEE et si je me rappelle bien aussi dans certains communiqués ARS , les nombres de personnes issues du Haut Rhin sont en très faible nombre , même si il est probable que la proximité avec le fameux lieu du rassemblement évangélique explique sans doute le résultat. 
Par contre l’hôpital du Territoire de Belfort s'appelle Hôpital Nord Franche Comté , il est le résultat du regroupement des Hôpitaux situés auparavant à Belfort et Montbéliard, et donc il regroupe les patients du 25, du 90 mais aussi du 70 (Héricourt par exemple) 
Donc les habitants du  Territoire de Belfort  représentent moins de 50% des patients de l’hôpital. Inversement, le Doubs ne décompte pas dans ses statistiques ceux de Montbéliard .

Donc je partage votre souci sur le principe , mais il faudrait peut être raisonner par hôpital et avoir une analyse des bassins de drainage de ces hôpitaux  pour en tirer des informations pertinentes.  
Sachant qu'en période de crise , le dispatching vers un hôpital moins en tension, même plus éloigné, peut aussi fausser l'interprétation (à l’extrême : ce qui s'est passé dans les transferts interrégionaux)

**Comment by htonchia** [comment]
Merci pour l'information pour l'hôpital de Belfort.

Il faudrait effectivement connaître le bassin de drainage des hopitaux.
Le dispatching dans une même région et même entre les régions fausse les résultats très locaux. C'est d'ailleurs qui motive le gouvernement quand il choisit de considérer la tension hospitalière par région et non par département. 

La crise fausse aussi les résultats lorsqu'une clinique privée sans réanimation est transformée en hôpital soignant des malades du COVID-19 après mise en place d'une salle de réanimation dédiée et de lits pour les patients dits "non réanimatoires".
