### ISSUE TITLE
Surmortalité positive vs négative

### ISSUE THREAD

**Issue by yoch** [htonchia/covid-19-France#2]
Tout d'abord merci pour cette présentation des données.

Je ne comprends pas vraiment les concepts exposés dans les tableaux du fichier `Surmortalité détaillée par lieu du décès et commune`, ni la méthode pour y parvenir.

Comment sont calculés les chiffres de surmortalité positive et négative ?
Si, comme le titre semble l'indiquer, on calcule l’écart de mortalité sur la période donnée pour chaque commune et l'on agrège les résultats positifs d'un coté et négatifs de l'autre, je ne vois pas bien ce que cela pourrait signifier. Car de façon générale, une commune offre un échantillon de taille bien trop réduite pour que ces chiffres aient une signification statistique (près de 3/4 des communes ont moins de 1000 habitants).

Autre point, j'ai refait ces calculs sur la période du 01/03 au 27/04 et j'obtiens des valeurs très différentes pour une surmortalité totale similaire. Par exemple pour l’écart des décès au logement par commune, je trouve 7992 - 2251 = 5741.

**Comment by htonchia** [comment]
Merci pour le commentaire. 

Pour le concept des tableaux, je vais réfléchir à comment clarifier cela.
L'idée est de regarder les communes qui ont une surmortalité positive et de faire la somme de celle-ci et la même chose pour celles qui ont une surmortalité négative.
Finalement, cela montre la variabilité à ce niveau de détail ce qui est une information en soi. L'idée était de séparer les communes touchées par le COVID, des autres. 

Je n'ai pas gardé les calculs, ni les données (au 20/04/2020), mais je les ai refaits. L'idée est bien celle-là on agrège d'un côté les communes avec une surmortalité au logement négative et de l'autre les autres.
Effectivement, la conclusion à en tirer est bien le manque de représentativité statistique. 
Par contre, même si cela n'est pas intéressant de façon générale puisque près de 3/4 des communes ont moins de 1000 habitants, cela devient très intéressant pour Paris et sa couronne.

Je viens de faire et refaire les calculs (pour la France métropolitaine) pour la période du 01/03 au 27/04 entre 2019 et 2020 et j'obtiens :
|                                                  |   Autres |   HopCli |   HosMar |   Logem |   Non renseigne |
|:-------------------------------------------------|---------:|---------:|---------:|--------:|----------------:|
| Surmortalité positive par commune métropolitaine |     1161 |    12434 |     9514 |   12876 |            4879 |
| Surmortalité négative par commune métropolitaine |    -1710 |    -3412 |    -3127 |   -6683 |           -2231 |
| Surmortalité totale métropolitaine               |     -549 |     9022 |     6387 |    6193 |            2648 |

Je n'arrive pas à trouver vos chiffres. J'ai fait les calculs en python.

L'intérêt de descendre au niveau communal est de comparer les communes autour de Paris et de voir s'il y a une corrélation avec la pauvreté du territoire comme le laisse entendre les médias.
Comme Neuilly-sur-Seine présente une forte surmortalité au logement, on ne peut l'expliquer par la pauvreté du territoire. [lien](https://github.com/htonchia/covid-19-France/blob/master/cartes_deces_hosp_nonhosp.md#cartographie-détaillée-des-hauts-de-seine-surmortalité-au-logement).

**Comment by yoch** [comment]
OK, j'ai compris pourquoi je n'obtenais pas le même résultat: les communes absentes d'une part ou de l'autre n’étaient pas comptabilisées.

J'ai refait le calcul (également en python avec pandas, code ci dessous) et je trouve effectivement des résultats très proches:

|          |   Autres |   HopCli |   HosMar |   Logem |   Non renseigne |
|:---------|---------:|---------:|---------:|--------:|----------------:|
| positive |     1191 |    12481 |     9546 |   13097 |            4962 |
| negative |    -1778 |    -3617 |    -3161 |   -6830 |           -2269 |
| total    |     -587 |     8864 |     6385 |    6267 |            2693 |

Mais ce tableau est finalement peu informatif, car il reflète plus une variabilité statistique qu'une véritable surmortalité. Un calcul par département est probablement plus représentatif de la véritable sous-mortalité:

|          |   Autres |   HopCli |   HosMar |   Logem |   Non renseigne |
|:---------|---------:|---------:|---------:|--------:|----------------:|
| positive |      135 |    10323 |     6539 |    6404 |            3005 |
| negative |     -722 |    -1459 |     -154 |    -137 |            -312 |
| total    |     -587 |     8864 |     6385 |    6267 |            2693 |

Par rapport à la corrélation régulièrement rapportée entre pauvreté et impact du covid19, ce n'est pas juste les médias, j'ai tout de même vu passer quelques papier scientifiques allant dans ce sens.
Il faudrait je crois vérifier avec une méthodologie plus poussée qu'une comparaison somme toute assez locale, il y a des tas de facteurs qu'il est difficile de prendre en compte sans les connaitre (ex. présence ou non d'EHPAD, etc.).
____

Mon code, je l’espère sans erreur cette fois:

```python
import pandas as pd

df = pd.read_csv('DC_jan2018-avr2020_det.csv', sep=';')

# insertion de la date
df['DTDEC'] = pd.to_datetime(
    df[['ADEC', 'MDEC', 'JDEC']].rename(columns={"ADEC": "year", "MDEC": "month", "JDEC": "day"})
)

df = df[['DTDEC', 'DEPDEC', 'COMDEC', 'LIEUDEC2']]

df2019 = df[df.DTDEC.between('2019-03-01', '2019-04-27')]
df2020 = df[df.DTDEC.between('2020-03-01', '2020-04-27')]

tbl2019 = df2019.pivot_table(index=df2019.COMDEC, columns=df2019.LIEUDEC2, fill_value=0, aggfunc='size')
tbl2020 = df2020.pivot_table(index=df2020.COMDEC, columns=df2020.LIEUDEC2, fill_value=0, aggfunc='size')

diff = tbl2020.subtract(tbl2019, fill_value=0)

positive = diff[diff>0].sum().rename('positive')
negative = diff[diff<0].sum().rename('negative')
total = diff.sum().rename('total')

table = pd.concat([positive, negative, total], axis=1)

print(table.T.to_markdown())
```

**Comment by htonchia** [comment]
Merci pour l'explication et le code qui est meilleur que le mien pour la gestion des dates, j'ai débuté panda pour analyser ces données et j'ai encore beaucoup à apprendre. 

Par contre, suite à cette discussion, je suis en train de produire les versions svg des cartes régionales pour lesquelles on pourra avoir le nom de la commune et le delta en survolant la carte à la souris. Cela m'a permis de détecter que Versailles est aussi en anomalie de surmortalité au domicile.
Effectivement, l'absence d'EHPAD ou le choix de rester à la maison, peut être une explication de la surmortalité au logement. C'est pourquoi j'ai pris en compte la surmortalité au logement pour calculer un indice de contamination au niveau départemental (mais pas les EHPAD) .

**Comment by yoch** [comment]
J’écris pour mentionner [ce post](https://blog.insee.fr/statistiques-sur-les-deces-le-mode-demploi-des-donnees-de-linsee-en-7-questions-reponses/) fort instructif sur le blog de l'INSEE, même si je n'ai pas vu qu'ils abordent explicitement la question de la granularité du calcul de surmortalité (j'ai peut être lu trop vite).

Sinon, autre point, les données publiées sont clairement trop peu consolidées, exemple depuis la MAJ du 15/05 les résultats ont quelque peu changé sur la période **du 01/03 au 27/04** :

### Par département

|          |   Autres |   HopCli |   HosMar |   Logem |   Non renseigne |
|:---------|---------:|---------:|---------:|--------:|----------------:|
| positive |      143 |    10452 |     6764 |    6888 |            3545 |
| negative |     -686 |    -1389 |     -132 |    -102 |            -287 |
| total    |     -543 |     9063 |     6632 |    6786 |            3258 |

### Par commune

|          |   Autres |   HopCli |   HosMar |   Logem |   Non renseigne |
|:---------|---------:|---------:|---------:|--------:|----------------:|
| positive |     1226 |    12623 |     9723 |   13477 |            5505 |
| negative |    -1769 |    -3560 |    -3091 |   -6691 |           -2247 |
| total    |     -543 |     9063 |     6632 |    6786 |            3258 |
